from stac_geoparquet.pgstac_reader import CollectionConfig

# TODO: verify chunk sizes

CONFIGS = {
    "3dep-lidar-classification": CollectionConfig("3dep-lidar-classification", "AS"),
    "3dep-lidar-copc": CollectionConfig("3dep-lidar-copc", "AS"),
    "3dep-lidar-dsm": CollectionConfig("3dep-lidar-dsm", "AS"),
    "3dep-lidar-dtm": CollectionConfig("3dep-lidar-dtm", "AS"),
    "3dep-lidar-dtm-native": CollectionConfig("3dep-lidar-dtm-native", "AS"),
    "3dep-lidar-hag": CollectionConfig("3dep-lidar-hag", "AS"),
    "3dep-lidar-intensity": CollectionConfig("3dep-lidar-intensity", "AS"),
    "3dep-lidar-pointsourceid": CollectionConfig("3dep-lidar-pointsourceid", "AS"),
    "3dep-lidar-returns": CollectionConfig("3dep-lidar-returns", "AS"),
    "3dep-seamless": CollectionConfig("3dep-seamless", None),
    "alos-dem": CollectionConfig("alos-dem", None),  # TODO: 23,997 records
    "alos-fnf-mosaic": CollectionConfig("alos-fnf-mosaic", "AS"),  # ~22,000 per year
    "alos-palsar-mosaic": CollectionConfig("alos-palsar-mosaic", "AS"),
    "aster-l1t": CollectionConfig("aster-l1t", "AS"),
    "chloris-biomass": CollectionConfig("chloris-biomass", None),
    "cil-gdpcir-cc-by": CollectionConfig("cil-gdpcir-cc-by", None),
    "cil-gdpcir-cc-by-sa": CollectionConfig("cil-gdpcir-cc-by-sa", None),
    "cil-gdpcir-cc0": CollectionConfig("cil-gdpcir-cc0", None),
    "cop-dem-glo-30": CollectionConfig("cop-dem-glo-30", None),
    "cop-dem-glo-90": CollectionConfig("cop-dem-glo-90", None),
    "eclipse": CollectionConfig("eclipse", None),
    "ecmwf-forecast": CollectionConfig("ecmwf-forecast", "MS"),
    "era5-pds": CollectionConfig("era5-pds", None),
    "esa-worldcover": CollectionConfig("esa-worldcover", None),
    "fia": CollectionConfig("fia", None),
    "gap": CollectionConfig("gap", None),
    "gbif": CollectionConfig("gbif", None),
    "gnatsgo-rasters": CollectionConfig("gnatsgo-rasters", None),
    "gnatsgo-tables": CollectionConfig("gnatsgo-tables", None),
    "goes-cmi": CollectionConfig("goes-cmi", "W-MON"),
    "hrea": CollectionConfig("hrea", None),
    "io-lulc": CollectionConfig("io-lulc", None),
    "io-lulc-9-class": CollectionConfig("io-lulc-9-class", None),
    "jrc-gsw": CollectionConfig("jrc-gsw", None),
    "landsat-c2-l1": CollectionConfig("landsat-c2-l1", "MS"),
    "landsat-c2-l2": CollectionConfig("landsat-c2-l2", "MS"),
    "mobi": CollectionConfig("mobi", None),
    "modis-09A1-061": CollectionConfig("modis-09A1-061", "MS"),  # ~2,000 items @ monthly
    "modis-09Q1-061": CollectionConfig("modis-09Q1-061", "MS"),
    "modis-10A1-061": CollectionConfig("modis-10A1-061", "MS"),
    "modis-10A2-061": CollectionConfig("modis-10A2-061", "MS"),
    "modis-11A1-061": CollectionConfig("modis-11A1-061", "MS"),
    "modis-11A2-061": CollectionConfig("modis-11A2-061", "MS"),
    "modis-13A1-061": CollectionConfig("modis-13A1-061", "MS"),
    "modis-13Q1-061": CollectionConfig("modis-13Q1-061", "MS"),
    "modis-14A1-061": CollectionConfig("modis-14A1-061", "MS"),
    "modis-14A2-061": CollectionConfig("modis-14A2-061", "MS"),
    "modis-15A2H-061": CollectionConfig("modis-15A2H-061", "MS"),
    "modis-15A3H-061": CollectionConfig("modis-15A3H-061", "MS"),
    "modis-16A3GF-061": CollectionConfig("modis-16A3GF-061", "MS"),
    "modis-17A2H-061": CollectionConfig("modis-17A2H-061", "MS"),
    "modis-17A2HGF-061": CollectionConfig("modis-17A2HGF-061", "MS"),
    "modis-17A3HGF-061": CollectionConfig("modis-17A3HGF-061", "MS"),
    "modis-21A2-061": CollectionConfig("modis-21A2-061", "MS"),
    "modis-43A4-061": CollectionConfig("modis-43A4-061", "MS"),
    "modis-64A1-061": CollectionConfig("modis-64A1-061", "MS"),
    "mtbs": CollectionConfig("mtbs", None),
    "naip": CollectionConfig("naip", "AS"),
    "nasa-nex-gddp-cmip6": CollectionConfig("nasa-nex-gddp-cmip6", None),
    "nasadem": CollectionConfig("nasadem", None),
    "noaa-c-cap": CollectionConfig("noaa-c-cap", None),
    "nrcan-landcover": CollectionConfig("nrcan-landcover", None),
    "planet-nicfi-analytic": CollectionConfig("planet-nicfi-analytic", "AS"),
    "planet-nicfi-visual": CollectionConfig("planet-nicfi-visual", "AS"),
    "sentinel-1-grd": CollectionConfig("sentinel-1-grd", "MS"),
    "sentinel-1-rtc": CollectionConfig("sentinel-1-rtc", "MS"),
    "sentinel-2-l2a": CollectionConfig("sentinel-2-l2a", "MS"),
    "us-census": CollectionConfig("us-census", None),
}